let testData = {
  success: true,
  message: '请求成功',
  code: 200,
  result: {
    合约中心: [
      {
        indexName: '合约中心',
        type: 1,
        id: '66',
        configId: '1',
        metric: 'app.TPS',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: 1,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS',
        allAlarmLevel: '1'
      },
      {
        indexName: '合约中心',
        type: 1,
        id: '65',
        configId: '1',
        metric: 'app.RTT',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: 2,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '合约中心',
        type: 1,
        id: '68',
        configId: '1',
        metric: 'app.SUCCESSRATE',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '合约中心',
        type: 1,
        id: '67',
        configId: '1',
        metric: 'app.ERROR',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ],
    管理后台: [
      {
        indexName: '管理后台',
        type: 1,
        id: '58',
        configId: '2',
        metric: 'app.TPS',
        endpoint: null,
        resultValue: null,
        alarmLevel: 1,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS'
      },
      {
        indexName: '管理后台',
        type: 1,
        id: '57',
        configId: '2',
        metric: 'app.RTT',
        endpoint: null,
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '管理后台',
        type: 1,
        id: '60',
        configId: '2',
        metric: 'app.SUCCESSRATE',
        endpoint: null,
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '管理后台',
        type: 1,
        id: '59',
        configId: '2',
        metric: 'app.ERROR',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ],
    策略柜台: [
      {
        indexName: '策略柜台',
        type: 1,
        id: '26',
        configId: '3',
        metric: 'app.TPS',
        endpoint: 'UF20_TD',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS'
      },
      {
        indexName: '策略柜台',
        type: 1,
        id: '25',
        configId: '3',
        metric: 'app.RTT',
        endpoint: 'UF20_TD',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '策略柜台',
        type: 1,
        id: '28',
        configId: '3',
        metric: 'app.SUCCESSRATE',
        endpoint: 'UF20_TD',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '策略柜台',
        type: 1,
        id: '27',
        configId: '3',
        metric: 'app.ERROR.NUM',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ],
    策略中心: [
      {
        indexName: '策略中心',
        type: 1,
        id: '46',
        configId: '4',
        metric: 'app.TPS',
        endpoint: null,
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS'
      },
      {
        indexName: '策略中心',
        type: 1,
        id: '45',
        configId: '4',
        metric: 'app.RTT',
        endpoint: null,
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '策略中心',
        type: 1,
        id: '48',
        configId: '4',
        metric: 'app.SUCCESSRATE',
        endpoint: null,
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '策略中心',
        type: 1,
        id: '47',
        configId: '4',
        metric: 'app.ERROR',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ],
    产品中心: [
      {
        indexName: '产品中心',
        type: 1,
        id: '50',
        configId: '5',
        metric: 'app.TPS',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS'
      },
      {
        indexName: '产品中心',
        type: 1,
        id: '49',
        configId: '5',
        metric: 'app.RTT',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '产品中心',
        type: 1,
        id: '52',
        configId: '5',
        metric: 'app.SUCCESSRATE',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '产品中心',
        type: 1,
        id: '51',
        configId: '5',
        metric: 'app.ERROR',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ],
    柜台dubbo服务: [
      {
        indexName: '柜台dubbo服务',
        type: 1,
        id: '62',
        configId: '6',
        metric: 'app.TPS',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 1,
        metricName: 'TPS'
      },
      {
        indexName: '柜台dubbo服务',
        type: 1,
        id: '61',
        configId: '6',
        metric: 'app.RTT',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 2,
        metricName: '平均耗时'
      },
      {
        indexName: '柜台dubbo服务',
        type: 1,
        id: '64',
        configId: '6',
        metric: 'app.SUCCESSRATE',
        endpoint: 'queryPrdtFeeMsg',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 3,
        metricName: '成功率'
      },
      {
        indexName: '柜台dubbo服务',
        type: 1,
        id: '63',
        configId: '6',
        metric: 'app.ERROR',
        endpoint: 'StrategyExeclog',
        resultValue: null,
        alarmLevel: null,
        ifIndex: '1',
        sortNum: 4,
        metricName: '失败数'
      }
    ]
  },
  timestamp: 1631152695190
};
